
train_episodes: 50000
random_action_steps: 1000
eval_episodes: 10
eval_every: 500

env_name: "Breakout-v0"
batch_size: 128
memory_size: 100000
frames_per_sample: 4
resolution: [84, 84]

model:
  gamma: 0.9
  epsilon: 0.9
  epsilon_min: 0.001
  epsilon_decay: 0.999

  input_channels: 4
  projection_dim: 256
  hidden_size: 256
  
  optim:
    lr: 0.0001
    betas: [0.9, 0.999]
    amsgrad: False

transform:
  resize:
    size: [84, 84]
  to_tensor: